name: EnergyMonitorApp
options:
  bundleIdPrefix: com.dolbec
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"

targets:
  EnergyMonitorApp:
    type: application
    platform: macOS
    sources:
      - Sources
    resources:
      - Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.dolbec.energymonitor
        PRODUCT_NAME: Energy Monitor
        MARKETING_VERSION: "1.5.23"
        CURRENT_PROJECT_VERSION: "173"
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        INFOPLIST_FILE: Resources/Info.plist
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGN_ENTITLEMENTS: Resources/EnergyMonitorApp.entitlements
        ENABLE_HARDENED_RUNTIME: NO
        LD_RUNPATH_SEARCH_PATHS:
          - "@executable_path/../Frameworks"
